### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by jobisoft** [grierforensics/Great-DANE-Engine#3]
Hi,

this sounds great and I want to try it out, but I am not able to follow your install instructions. Could you give a few more hints?

What I understood is that I have to build it first. How? Can I build it on a different system from where I want to run it?

What do I need to run it?

Sorry, but I am not used to java, thanks for your help!

**Comment by naegelejd** [comment]
I'll definitely improve the install instructions using your feedback.

The easiest way to install the Great DANE Engine is to download and run the installer hosted under [Releases](https://github.com/grierforensics/Great-DANE-Engine/releases). This works on Windows, Linux and OS X. On Linux and OS X you'll need to then run `greatdaneengine.sh start` from the `bin/` directory wherever you install it. What platform are you using?

If you'd prefer not to use the pre-built installer you'll need [SBT](http://www.scala-sbt.org/) which is the standard tool for compiling Scala software. Once you have `sbt` you can do one of the following:
- run `sbt pack` then run the service script at `./target/pack/bin/service`
- run `sbt pack-archive` then copy and unpack `./target/engine-1.0.zip` or `./target/engine-1.0.tar.gz`
- run `sbt izpack:create-installer` to build a cross-platform installer at `./target/installer.jar`

All that being said, to actually use the Great DANE Engine you'll need the ability to add an SMIMEA record to the DNS for your email address. I'm happy to help guide you through this procedure if you'd like.

**Comment by jobisoft** [comment]
Ok, that does help indeed, I will try to get it running on my debian jessy and report back, if I still have problems.

I do have an SMIMEA record for my (private) email in my DNS.

Thanks for the Thunderbird Plugin as well! (That is how I found your work)

**Comment by naegelejd** [comment]
Excellent, I look forward to your feedback. I'm also working on improvements (including instructions for how to obtain the Engine) to the Thunderbird Add-On, so please feel free to leave feedback, critical or otherwise, for that too!
